"""Add user_id to jobs

Revision ID: 09204c156863
Revises: 1f2d10aa9401
Create Date: 2025-05-25 17:19:51.658462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09204c156863'
down_revision: Union[str, None] = '1f2d10aa9401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
