version: "3.8"

services:
  db:
    image: postgres:15-alpine # You can choose a specific version
    container_name: cjb_postgres_db
    restart: always
    environment:
      POSTGRES_USER: cjb # Change this
      POSTGRES_PASSWORD: cjb # Change this
      POSTGRES_DB: cjb_db # Change this
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
